// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingManagementSystemAPI.Data;

#nullable disable

namespace ParkingManagementSystemAPI.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20240107134805_seedingData")]
    partial class seedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.ParkingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTypeName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("VehicleTypeName");

                    b.ToTable("ParkingAssignments");
                });

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.ParkingSlot", b =>
                {
                    b.Property<int>("SlotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotNumber"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SlotType")
                        .HasColumnType("int");

                    b.HasKey("SlotNumber");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            SlotNumber = 1,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 2,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 3,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 4,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 5,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 6,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 7,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 8,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 9,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 10,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 11,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 12,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 13,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 14,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 15,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 16,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 17,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 18,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 19,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 20,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 21,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 22,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 23,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 24,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 25,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 26,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 27,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 28,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 29,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 30,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 31,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 32,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 33,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 34,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 35,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 36,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 37,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 38,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 39,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 40,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 41,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 42,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 43,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 44,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 45,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 46,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 47,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 48,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 49,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 50,
                            IsAvailable = true,
                            SlotType = 0
                        },
                        new
                        {
                            SlotNumber = 51,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 52,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 53,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 54,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 55,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 56,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 57,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 58,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 59,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 60,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 61,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 62,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 63,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 64,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 65,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 66,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 67,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 68,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 69,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 70,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 71,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 72,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 73,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 74,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 75,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 76,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 77,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 78,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 79,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 80,
                            IsAvailable = true,
                            SlotType = 1
                        },
                        new
                        {
                            SlotNumber = 81,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 82,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 83,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 84,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 85,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 86,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 87,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 88,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 89,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 90,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 91,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 92,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 93,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 94,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 95,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 96,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 97,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 98,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 99,
                            IsAvailable = true,
                            SlotType = 2
                        },
                        new
                        {
                            SlotNumber = 100,
                            IsAvailable = true,
                            SlotType = 2
                        });
                });

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.VehicleType", b =>
                {
                    b.Property<string>("VehicleTypeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompatibleSlotTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleTypeName");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            VehicleTypeName = "Hatchback",
                            CompatibleSlotTypes = "[0,1,2]"
                        },
                        new
                        {
                            VehicleTypeName = "Sedan/Compact SUV",
                            CompatibleSlotTypes = "[1,2]"
                        },
                        new
                        {
                            VehicleTypeName = "SUV or Large cars",
                            CompatibleSlotTypes = "[2]"
                        });
                });

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.ParkingAssignment", b =>
                {
                    b.HasOne("ParkingManagementSystemAPI.Models.ParkingSlot", "Slot")
                        .WithMany("ParkingAssignments")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagementSystemAPI.Models.VehicleType", null)
                        .WithMany("ParkingAssignments")
                        .HasForeignKey("VehicleTypeName");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.ParkingSlot", b =>
                {
                    b.Navigation("ParkingAssignments");
                });

            modelBuilder.Entity("ParkingManagementSystemAPI.Models.VehicleType", b =>
                {
                    b.Navigation("ParkingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
